### PR TITLE
feat(core): new build system, fix treeshaking

### LINKED ISSUE #130: [Perf] unneeded files are being included in the final bundle
* **I'm submitting a ...**
[x ] feature request

* **What is the current behavior?**

When running a bundle analyzer I found that files for all analytics providers were being included. Event though I was only using one.
ie: appinsight, mixpanel, Ga, kissmetrics, etc

* **What is the expected behavior?**

I would like the final bundle to only include the files I'm using. So if i'm just adding support for GA, then all the other providers won't end up in the final bundle.

nb: I've seen other libraries solve this by providing the different providers as separate modules.

* **What is the motivation / use case for changing the behavior?**

To reduce the final size of my webapp.

* **Please tell us about your environment:**

- Angular version: 4.1.3
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I added this in the app.module file.

`Angulartics2Module.forRoot([Angulartics2Mixpanel]),`

### LINKED ISSUE #149: Link in package is to http://angulartics.github.io/ should be http://angulartics2.github.io/
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

The link in the package that shows up in npm or yarn outdated is to http://angulartics.github.io/ (which is currently at version 1.4). The link should be to http://angulartics2.github.io/

It's confusing when an update is available and the link to the release notes is to the wrong repo.

### PR DESCRIPTION
**Pull request by scttcper**
fixes #130 Changes are breaking for all existing users

build.ts handles all bundling using rollup and angular compiler. Heavily based on angularfire2's build.js https://github.com/angular/angularfire2/blob/master/tools/build.js All of the providers now import Angulartics2 using typescript paths instead of relative paths, when compiled this tells webpack to import from the global require('angulartics2'). import 'rxjs/add/operator/filter' is now `import { filter } from 'rxjs/operator/filter';` which is more AoT compiler friendly. the forChild method has also been removed since it does nothing

This build format enables one provider to be imported at a time and make smaller bundles
```ts
import { Angulartics2Module } from 'angulartics2';
import { Angulartics2GoogleAnalytics } from 'angulartics2/ga';
// or
import { Angulartics2AdobeAnalytics } from 'angulartics2/adobeanalytics';
```
everything else is pretty much the same.

I wasn't using the existing webpack build system, so the test system stopped working as well. I've put the codebase into angular-cli to handles test, it can also be used to build docs.

The main additions are package.json, tsconfig-build.json, tsconfig-esm.json which are necessary for every subpackage. This also uses rollup to create a folder of umd bundles for each package and format exports into a format recommended by the angular team

fixes #149 w/ the links 
adds `@types/google.analytics` for type checking on ga

Sorry if this pull request is too big. Changing the build system, turned into needing to fix the test runner and it just never ended.

### CODE REVIEW

**Comment by scttcper** [comment]
I've put just the build on github https://github.com/scttcper/angulartics2-build

```bash
npm i scttcper/angulartics2-build
```

**Comment by ZuSe** [comment]
Looks good to me.
Fixes also some of the opened tickets.

**Comment by smoke** [comment]
Looks good to me also. 
I think this fixes also https://github.com/angulartics/angulartics2/issues/138

**Comment by scttcper** [comment]
gah didn't squash

**Pull request merged**
