### PR TITLE
Add Adobe Analytics (Omniture) Provider

### PR DESCRIPTION
**Pull request by mer10z**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adds provider for Adobe Analytics that supports page and event tracking.

* **What is the current behavior?** (You can also link to an open issue here)
Adobe Analytics not currently supported #110 

* **What is the new behavior (if this is a feature change)?**
Adobe Analytics support.

* **Other information**:

### CODE REVIEW

**Comment by mer10z** [comment]
What is the processes for getting this merged?

**Comment by JonnyBGod** [comment]
Sorry for the late response and than you for the PR.

**Comment by mer10z** [comment]
No problem, thanks!

**Comment by nkarri** [comment]
Can you please provide more details on how to include AdobeAnalytics in angulartics2 including setting up the account information. 
https://github.com/angulartics/angulartics2/issues/117

**Comment by dafabulousteach** [comment]
Exactly where does the s_account value go?

**Pull request merged**
