### PR TITLE
fix(Window): removes implicit dependency on window

### PR DESCRIPTION
**Pull request by NathanWalker**
closes https://github.com/angulartics/angulartics2/issues/9

The following would have been done in separate PR but it needed it all:
* Update to beta.11
* Using `typings` to manage typings
* Simplified npm setup
* Tighter testing setup and verified tests 100% (*some previous tests did not work actually*)

### CODE REVIEW

**Comment by NathanWalker** [comment]
This needs some more work. I'll fix up the other details to cleanup tests.
I'm needing these changes for a project I'm working on.

**Comment by JonnyBGod** [comment]
Thanks for PR. I will have a closer look as soon as I get the time.

Problem ATM is that most tests are broken since zones have been temporarily switched off from testing environment.

I have been waiting for Angular2 guys to reimplement zones and reactivate it on testing environment. Apparently beta.10 uses new zone 0.6.x implementation. Hoping to have them working with tests soon.

**Comment by NathanWalker** [comment]
Last commit helps dry up some testing code. Still working with it, should be able to test this just find with zones, etc. May need to adjust the spy. You might pull the fork tied to this PR to have a look, lemme know what ya' think. After cloning fork:
```
npm install
npm test
```

You'll see a bunch of duplicate identifier warnings from TS and then the test failures around the spies.
We can fix the warnings soon; may just need your help getting the spies adjusted.

**Comment by NathanWalker** [comment]
@JonnyBGod Got things fixed up and super tight with all tests passing. Even improved the tests quite a bit (*some previous ones did not work properly*).

* removed window dependency completely
* updated to `beta.11` with zone `0.6.5`.
* dried up tests a ton
* ensured all async testing used proper promises to ensure correct test order firing

Let me know if you could merge, bump, and publish new version. Cheers!

**Comment by JonnyBGod** [comment]
Great work. Will have a closer look tonight.

Quick remarks:
1. I don't really like the idea of having an index file including all providers. The point of my previous architecture was to keep provider included in the module for easy management but keep them separate and optional while easy to import (Angular2 way).

2. Please reflect changes in documentation.

I will have to think a bit on first point. But will probably ask you to change it back or at least separate into two PRs for further discussion.

Apart from it thank you for fixing the tests.

**Comment by NathanWalker** [comment]
Thanks. Agreed on above. Just pushed the changes you mentioned.

* index is how you had it originally now
* changes reflected in documentation

BEFORE:
```
'angulartics2/providers/angulartics2-google-analytics'
```

AFTER:
```
'angulartics2/src/providers/angulartics2-google-analytics'
```

:+1:

**Comment by JonnyBGod** [comment]
Sorry for delay, bit busy these days.

So Everything looks good. Just one last point:

What is your rationale for changing release format? I mean, I had intentionally made the release so that src would not be downloaded and the structure would be similar to angular2 have a core path and a providers path on root for easy and clean integration.

I pretty much prefer ```'angulartics2/providers/angulartics2-google-analytics'``` to ```'angulartics2/src/providers/angulartics2-google-analytics'```.

Also I don't see the point of downloading the full source for production environments.

Any rational behind this change?

**Comment by NathanWalker** [comment]
It was just a simplification and to actually be consistent with `angular2` project.
For example, they provide several services that are not part of the `bundle` per say, but more ala' carte, like:
```
import {RootRouter} from 'angular2/src/router/router';
```

Was just going with that strategy.
That way the main import provided the core (bundled if you will) services/directive.
But you had the option to import the ala' carte services for whichever you need.
It might make more sense to make those separate npm modules and not part of the `core` module here, but that's maybe for down the road.

I'm good with whatever way you want to go with, but that's ^ my rationale :+1:

**Comment by NathanWalker** [comment]
Oh and you wouldn't be 'downloading the full source for production environments' because the npm module when published only provides the "compiled" .js files so no source.

Additionally the way you had it before still brought down everything in the npm install, it was just in a different directory.

**Comment by NathanWalker** [comment]
Lastly, regarding "providers path on root for easy and clean integration", this is still the case:
https://github.com/NathanWalker/angulartics2/blob/master/index.ts

**Comment by JonnyBGod** [comment]
I think this will need a bit more thinking but for now we will go with it.

**Comment by NathanWalker** [comment]
I can try installing from the merged commit and see how the setup is to best figure out what else we may want to do? I'll let ya' know what I find out.  Lemme know your thoughts on if we should break out the extra provider services into separate npm modules, I could help you with that?  That way a user only installs what they want with nothing extra.

**Comment by NathanWalker** [comment]
Just realized I won't be able to from the commit since the .ts would not be compiled.
If you want to publish a version, we can look at it, and make quick adjustment based on what we find.

**Comment by JonnyBGod** [comment]
For now I think it is easier to maintain one repo instead of several. The overhead of installing all providers is small atm. I am more concerned with overhead in production, I mean make it possible to import just what you need for your client.

**Comment by NathanWalker** [comment]
Agree, n/p!  You just let me know how I can help whenever. Also, I think I can just compile latest master locally and then experiment with it in a new project as if it were installed from npm to see how everything will pan out.

**Comment by JonnyBGod** [comment]
I just tested latest release with this PR included and everything looks fine. Also updated dependencies and bumped to angular2 beta.12 support.

Thank you for you help here. You saved me a lot of work.

For now we just need to keep it up to date with angular2 changes and maybe implement a few new provider in a need demand basis.

**Comment by NathanWalker** [comment]
nice! Sounds good thanks!

**Pull request merged**
