### PR TITLE
fix(ga): expose ga settings in ga provider #87

### LINKED ISSUE #87: Many trackers on one page
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/angulartics2)

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

Google support to send events to many trackers.
https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers

ga('create', 'UA-XXXXX-Y', 'auto');
ga('create', 'UA-XXXXX-Z', 'auto', 'clientTracker');

ga('send', 'pageview');
ga('clientTracker.send', 'pageview');

It is possible in angulartics2?

### PR DESCRIPTION
**Pull request by rossedfort**
- **What kind of change does this PR introduce?**
* Add a feature to the ga provider.
- **What is the current behavior? Link to open issue?**
* No way to set `additionalAccountNames` on `settings` config object. #87 
- **What is the new behavior?**
* A new method in the google analytics provider that allows a user to set a list of additional account names. These account names are used in any subsequent tracking events, exceptions, etc.

closes #87

### CODE REVIEW

**Comment by rossedfort** [comment]
This is an updated re-write of #88

**Comment by scttcper** [comment]
Does this have an advantage over setting it directly?

```ts
this.angulartics2.settings.ga.additionalAccountNames = ['1', '2']
```

**Comment by rossedfort** [comment]
@scttcper I didn't realize you can access the Google Analytics provider settings from the main Angulartics2 service. Now that I do, this PR is kind of pointless. However, it does provide one nice advantage, in that before I only had to inject my provider into my main AppComponent, and now, I have to the inject the Provider and the Angulartics2 Service.

**Comment by scttcper** [comment]
But then every setting on every provider will want a setter in core and it'll just never end. maybe could make the ga specific settings public inside of the provider.

**Pull request merged**
