### PR TITLE
App Insights Provider

### PR DESCRIPTION
**Pull request by hikirsch**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
#40 

* **What is the new behavior (if this is a feature change)?**
Feature was implemented with tests.

* **Other information**:

### CODE REVIEW

**Comment by hikirsch** [comment]
i have no idea why this build is failing. any ideas?

**Comment by JonnyBGod** [comment]
It is strange indeed. It passes all tests locally. Seams like a problem with travis.

**Comment by hikirsch** [comment]
i wonder if it's the version of chrome, we're on version 55 and it seems from the travis output its on version 37.

**Comment by JonnyBGod** [comment]
Would you mind waiting a few days for their fix to be release?

**Comment by hikirsch** [comment]
no problem. thanks!

**Pull request merged**
