### PR TITLE
rc.1 compatibility - ready

### PR DESCRIPTION
**Pull request by NathanWalker**
rc.1 compatibility. If this looks good to you, then please merge.
It removes all reliance on `Router` and just relies on `Location`.
`Router` is still used in tests just to setup components, however only `Location` is used to transition location changes.

All tests are passing.

Only 4 tests are disabled since the initial page track was only fired via the `Router` initializing.
This can be revisited in the future but is good now.
May want to update documentation to state the you need to track the initial page, however maybe not as `Location` may fire it's emitter on initialization of the route. I say we merge this to release a new version and I can try it out fully in an app.

### CODE REVIEW

**Comment by NathanWalker** [comment]
I'll squash the commits shortly.

**Comment by timelf123** [comment]
Great work, thanks!

**Comment by NathanWalker** [comment]
@JonnyBGod Lemme know if you can get to this today? I can merge shortly if not.

**Comment by JonnyBGod** [comment]
Hoping to get to it in a few hours.

{ name: “João Ribeiro”,
  email: “jonnybgod@gmail.com <mailto:jonnybgod@gmail.com>”,
  phone: “+351 916 002 675 <tel:+351916002675>”,
  skype: “jmn_ribeiro <skype:jmn_ribeiro?add>”,
  linkedin: “https://pt.linkedin.com/in/jmnribeiro <https://pt.linkedin.com/in/jmnribeiro>”
  github: “https://github.com/JonnyBGod <https://github.com/JonnyBGod>” }

**Comment by JonnyBGod** [comment]
Cool looks good! Lets merge and manually check for inicial tracking.

**Pull request merged**
