### PR TITLE
feat: Google Global Site Tag

### PR DESCRIPTION
**Pull request by adrianduke**
- **What kind of change does this PR introduce?**
New provider to support Google Analytics new default tracker Global Site Tag

- **What is the current behavior? Link to open issue?**
#272 #155

- **What is the new behavior?**
Replica of the GTM module sans the `userID` method. Supports Page View, Custom Events and Exceptions.

### CODE REVIEW

**Comment by adrianduke** [comment]
Anything I can do to help speed up the merge?

**Comment by scttcper** [comment]
@adrianduke i'm waiting to hear back from the project owner about getting a new npm token for publishing. npm invalidated the one we were using in july

**Comment by developcodeza-matthew** [comment]
Hey @scttcper. Any updates on getting the new npm token. Just wondering how far gst support is? Not exactly sure how it all works but would this be added to the 'next' branch initially and then only to the main branch at a later stage?  Wondering whether I should wait a bit or rather change over to analytics.js in the mean time.

Thanks for all the hard work, much appreciated!

**Comment by scttcper** [comment]
looks like its working

**Pull request merged**
