### PR TITLE
fix(core): upgrade to angular 5 and typescript 2.6.x

### PR DESCRIPTION
**Pull request by scttcper**
BREAKING CHANGES: raises minimum Angular version to Angular 5

### CODE REVIEW

**Comment by jdpnielsen** [comment]
Any chance you could cut a release of this soonish?
I'm looking to use this in my angular 5 project.

Please let me know, if there is anything i can do to help expedite the process.

**Comment by scttcper** [comment]
@jdpnielsen there shouldn't be any issues with the current version w/ angular 5

**Comment by jdpnielsen** [comment]
Wierd. I'm getting a `StaticInjectorError(ServerAppModule)[RouterlessTracking -> Router]:` error when following the basic instructions found in the readme. Might be due to my setup (using ssr), but i used the same setup in angular 4 without issues.

**Comment by scttcper** [comment]
@jdpnielsen maybe make sure v4.6.3 is installed. There was issues with 4.6.2 and .1

I'll merge this in soon though.

**Comment by jdpnielsen** [comment]
Thanks. I'm on 4.6.3 - ill await the merge & release. If it doesn't solve the issue ill try and make a repo or something for reproducing the error.

**Comment by returnlytom** [comment]
@jdpnielsen Following up to Scott's comment (https://github.com/angulartics/angulartics2/pull/218#issuecomment-358692072), we have been using `4.6.3` with Angular `5.2.1` and it seems to be working as expected.

**Pull request merged**
