### PR TITLE
Facebook provider

### PR DESCRIPTION
**Pull request by rigoleto**
Let me know if I can improve anything!

### CODE REVIEW

**Comment by JonnyBGod** [comment]
Thank your for your PR.

We use [semantic-release](https://github.com/semantic-release/semantic-release) in our CI flow and for it to work properly please follow the [AngularJS Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit).

**Comment by rigoleto** [comment]
Commit message updated

**Comment by JonnyBGod** [comment]
Can you update your PR for rc.1 support? We just published a new version for it.
Also have a look to new tests implementation based on location instead of router.

**Comment by JonnyBGod** [comment]
This was added in [v1.4.0](https://github.com/angulartics/angulartics2/releases/tag/v1.4.0)

**Pull request closed without merging**
