### PR TITLE
feat(provider): GA enhanced ecommerce support

### PR DESCRIPTION
**Pull request by kontrollanten**
This adds GA enhanced ecommerce support till angulartics2

BREAKING CHANGE: Added ecAddImpression, ecAddProduct and ecSetAction to Angulartics2GoogleAnalytics

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Added GA enhanced ecommerce support.

* **What is the current behavior?** (You can also link to an open issue here)
No ecommerce support.

* **What is the new behavior (if this is a feature change)?**
Added GA enhanced ecommerce support.

* **Other information**:
Relatied with https://github.com/angulartics/angulartics2/issues/90 and https://github.com/angulartics/angulartics2/issues/34

### CODE REVIEW

**Comment by JonnyBGod** [comment]
My main concern is to understand if it makes sense to have this included on standard GA provider or if it should be a separate provider.

GA is probably the most used provider and should be as small and optimised as possible. It seams to me that E-Co functionality is important for some but neglitible for most. So probably best to keep GA provider as is and create a new one for GA with E-Co.

What is your opinion on this?

**Comment by kontrollanten** [comment]
@rolandoldengarm True, don't know why it got marked as breaking. 

@JonnyBGod I agree, since Google Analytics Enhanced Ecommerce is an addon to GA it's reasonable that it's a separate provider. 

I'll lift it out and make a new commit.

**Comment by galuszkak** [comment]
Looks great! Will be this merged? 👍

**Comment by galuszkak** [comment]
If I can give an input. Is it possible that some event's could be generalised? For example FB Pixel have AddToCart and here is action AddToCart (add product) also. It's same action, little different format of data send to provider. 

For now sounds to me I will send same events to different providers with different data. Especially with ecommerce events like:
AddToCart
RemoveFromCart
Checkout
Purchase
Details 

Maybe we should have some middle format for all providers that is later translated to provider format?

**Comment by kontrollanten** [comment]
@galuszkak Sounds reasonable. But I don't have time right now to fix that, maybe in the future :)

**Comment by chi-aevoe** [comment]
Hello, any news on this change?

**Comment by kontrollanten** [comment]
@rolandoldengarm Are you waiting for something from me?

**Comment by asgerjensen** [comment]
+1, lets get this included

**Comment by rolandoldengarm** [comment]
Looks good to me, what about you @JonnyBGod ?

**Comment by jonyeezs** [comment]
would you require to run `ga('require', 'ec');` in `<script>`? Or should be initiated when the service gets instatiated (knowing for fact that it is always provided on root).

**Comment by scttcper** [comment]
For some reason semantic release bumped and released this under v3.0.0

**Pull request merged**
