### PR TITLE
Rc5 router fix courtesy @rolandoldengarm

### PR DESCRIPTION
**Pull request by timelf123**
PR for discussion purposes
https://github.com/angulartics/angulartics2/issues/52

### CODE REVIEW

**Comment by JonnyBGod** [comment]
Thanks for the PR.

You are bundling a bunch of different stuff into a single PR and some need further discussion.

I am cool with RC5 and router fix, also _gaq fix though this needs to pass tests or remake tests to work with it.

Regarding the "specify version", "remove .npmignore" and "include build files", I would say we should discuss this. I opted not to include build files cons it looks to me like a bad practice to have production only files on a developing repo. This is taken care by the CI system by generating the build and packing the release. This way we have a clean repo to work with and have a full release with all the code.
In my opinion we should keep master as is regarding the build files. If we need a temporary fix branch that would not be registered to NPM, we can include build files on that specific branch for easy usage.

I would like to hear your thoughts on this @timelf123 @NathanWalker @rolandoldengarm 
Should we merge this?
Should we keep it as a separate temporary branch and maybe incorporate parts of it into master?

**Comment by rolandoldengarm** [comment]
It was no way meant to be a PR into your master.
E.g. those changes to remove version, remove .npmignore, etc. etc. was just meant to allow me to npm install from Github directly.
My repo was just meant as a temporary solution to make it work with RC5, until Angular has fixed the issue. Some useful things you could leverage:

- The _gac fix was something I fixed while doing that; that fix could already be merged into master. 
- The readme could also be used, as it shows how to use it in an RC5 ngModule.

**Comment by JonnyBGod** [comment]
Cool. Would you like to make a PR with both changes to be merged? Or I can copy it and make it myself, but would prefer for the author to do it.

**Comment by JonnyBGod** [comment]
Also, if you do make the PR, make sure you include the reference for your temporary fix into readme.md

**Comment by rolandoldengarm** [comment]
I'll work on the different PR's.

**Pull request closed without merging**
